### ISSUE TITLE
More info needed how this should work

### ISSUE THREAD

**Issue by conradhagemans** [analogic/lemanager#2]
I tried to setup LE-manager up without docker. I had to install composer. LE-manager is haevily depending on it. 
What I did:
- create a new directory in /etc/www/html/lemanager
- git clone git://server1.cyberciti.biz/analogic/lemanager
- curl -s https://getcomposer.org/installer | php
- php composer.phar

Then the basic is installed. Now you can open the webpage with https://domain/lemanager/index.php

I get it more or less working. All calls to other pages are done without .php extension. I added them.
Next by default LE-manager is looking in de /data directory for certificates.
I have them installed add /etc/letsencrypt/live/DOMAIN-NAME. Where to changes this?
I have running about 15 domains/websites on the server.
How to get it running with existing certificates?

**Comment by conradhagemans** [comment]
Small typo:

Now you can open the webpage with https://domain/lemanager/web/index.php

Forgot the /web sub-folder

**Comment by ToeiRei** [comment]
You might be missing a "php composer.phar install" in your first comment.

**Comment by conradhagemans** [comment]
Thanks. I will try it out.

**Comment by ToeiRei** [comment]
you noticed the nginx and other config fragments?
